### ISSUE TITLE
Can't run the .py

### ISSUE THREAD

**Issue by Quessts** [ohyicong/recaptcha_v2_solver#1]
Hey when I run the .py file I get this error
![Screenshot (36)](https://user-images.githubusercontent.com/54684166/97590720-f90ad380-1a0f-11eb-83a9-11297f138364.png)
I currently run python version 3.6.3

**Comment by ohyicong** [comment]
Did you pip install ffmpeg?

**Comment by ohyicong** [comment]
can I see the packages you installed?

**Comment by Quessts** [comment]
Yup I have installed ffmpeg and even got python 3.9. I'm pretty sure I got them all. Only thing I could think of is perhaps the speech_recognition package. I got a pip error when I tried downloading it so I did pip install SpeechRecognition

**Comment by ohyicong** [comment]
Do you have google chrome installed?

**Comment by Quessts** [comment]
Yes I do it's running Version 86.0.4240.111 (Official Build) (64-bit)
I also have Version 84 of the web driver

**Comment by ohyicong** [comment]
You need to update the chromedriver.exe in the webdriver folder to Version 86. Please download and replace it from https://chromedriver.chromium.org/downloads

**Comment by Quessts** [comment]
Thanks this worked. But after a couple of tried it displays this:
![Screenshot (38)](https://user-images.githubusercontent.com/54684166/97723388-c975cd00-1adc-11eb-96c2-f710660a55c6.png)

**Comment by ohyicong** [comment]
This is not a coding issue, recaptcha blocks your access after a few attempts. You have to use VPN or add more delays to the program.

**Comment by ChenPaulYu** [comment]
> Thanks this worked. But after a couple of tried it displays this:
> ![Screenshot (38)](https://user-images.githubusercontent.com/54684166/97723388-c975cd00-1adc-11eb-96c2-f710660a55c6.png)

Hey Quessts , 

I also have the same problem. Did you find the solution ?

**Comment by Quessts** [comment]
Nope. Sorry

**Comment by ohyicong** [comment]
Sorry, this is not a bug/glitch, google's algorithm is just too good. Haven't found a way to overcome this yet.
