### ISSUE TITLE
how to configure recaptcha_solver_dynamic_ip_mac.py? I got TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by MarkBone** [ohyicong/recaptcha_v2_solver#11]
[INFO] *Default Network Details*
[INFO] IP Address:  192.168.1.131
[INFO] Mask:  255.255.255.0
[INFO] Gateway:  192.168.1.253
Traceback (most recent call last):
  File "C:\Users\Jhon\Desktop\CODE\recaptcha_solver_dynamic_ip_mac.py", line 75, in <module>
    ip_address, mask, gateway = get_default_network_details()
TypeError: cannot unpack non-iterable NoneType object

**Comment by ohyicong** [comment]
Hi, this module is not ready yet. Please use recaptcha_solver.py instead.
