### ISSUE TITLE
[ERR] Unable to find recaptcha. Abort solver.

### ISSUE THREAD

**Issue by ghost** [ohyicong/recaptcha_v2_solver#14]
Getting this error when trying it out: [ERR] Unable to find recaptcha. Abort solver.

Is having the captcha in non english maybe the problem?

**Comment by ohyicong** [comment]
what website did you visit?

**Comment by ghost** [comment]
The default website inside the file https://www.google.com/recaptcha/api2/demo I also tried to add a 5 second sleep so the recaptcha is guranteed to appear (which I saw) but it still throws the same error

**Comment by ohyicong** [comment]
What is your chrome version?

**Comment by ohyicong** [comment]
I couldn't replicate the error

**Comment by ghost** [comment]
Latest stable chrome (94.0.4606.81) and webdriver ( https://chromedriver.storage.googleapis.com/index.html?path=94.0.4606.61/ )

**Comment by ghost** [comment]
> 
> 
> I couldn't replicate the error

Can you try downloading the repo yourself with a clean install? I have just downloaded the repo, installed the requirements for windows and ran it, I dont see what could have went wrong

**Comment by ohyicong** [comment]
Yes of course I did, there is no error at all. I used python 3.8 and Chrome Version 94.

**Comment by ohyicong** [comment]
The recaptcha will only work in english
