### ISSUE TITLE
"Your computer may be sending automated queries"

### ISSUE THREAD

**Issue by rozidev** [ohyicong/recaptcha_v2_solver#16]
is there any solution? so that google recaptcha doesn't read my computer as an automatic query sender, I often come across such notifications that make this tool not run and then stop

**Comment by ohyicong** [comment]
I'm looking into it

**Comment by ohyicong** [comment]
Recently, I added TOR functionality into the code. It has a 10% success rate in bypassing the "automatic query sender" issue
