### ISSUE TITLE
hello, please help me to solve these 2 issues...

### ISSUE THREAD

**Issue by we9designer** [ohyicong/recaptcha_v2_solver#2]
1. sample_audio = sr.AudioFile(os.getcwd()+"\\sample.wav")
it gives me this error "Module 'speech_recognition' has no 'AudioFile' member"

2. key=r.recognize_google(audio)
error is: Instance of 'Recognizer' has no 'recognize_google' member

I use Ubuntu 20.04, and Python 3.8.5

**Comment by ohyicong** [comment]
This script only works on windows pc.
