### ISSUE TITLE
Hello  netsh issue

### ISSUE THREAD

**Issue by Aoubd** [ohyicong/recaptcha_v2_solver#3]
[
Hello pro ,
thanks for great code 
I have this problem

INFO] IP Address:  192.168.100.41
[INFO] Mask:  255.255.255.0
[INFO] Gateway:  192.168.100.1
[INFO] *Changing MAC & IP*
[INFO] New Mac is: 0A:00:27:5D:F5:FC
/bin/sh: netsh: command not found
/bin/sh: netsh: command not found

I have MAC

**Comment by ohyicong** [comment]
This can only work for windows. Use the recaptcha_solver.py script instead.
