### ISSUE TITLE
"FileNotFoundError: [WinError 2] The system cannot find the file specified"

### ISSUE THREAD

**Issue by potatosearch** [ohyicong/recaptcha_v2_solver#8]
Whenever I run the .py file, it gets so far as to get the sample of audio but then gives me a FileNotFoundError
![image](https://user-images.githubusercontent.com/21028284/109810029-ed7b2380-7c20-11eb-8059-74869e64540b.png)

**Comment by BulNik** [comment]
Have same problem.

**Comment by ohyicong** [comment]
Hi, I have updated the code. Please run the program as administrator.
